# Generated by Django 2.0.6 on 2018-07-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='shared',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='texts',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
